### ISSUE TITLE
Project Development

### ISSUE THREAD

**Issue by ShadowManu** [jamesdixon/oh-my-jsonapi#15]
Hi. Before all, nice project going on here. My team requires a Bookshelf models -> json api responses, mapping tool. I liked this project (and the serializer project behind) and plant to use it as a base. 

However, changes like using Typescript and more testing (you know 4 tests is not enough) are features we want to set on the tool. What's your view on this? Do you prefer it to simply be a fork or are more interested on integration to the project?

**Comment by jamesdixon** [comment]
@ShadowManu thanks!

I'd be interested in having someone else collaborate on the project. I'm certainly aware that there isn't 100% coverage with the tests, but unfortunately due to a number of deadlines on my side, I haven't been able to create a full test suite. I'd gladly welcome some assistance on that front.

Regarding converting the project to Typescript, I'm not 100% opposed to doing so, but given that my familiarity with Typescript is extremely limited, I'd prefer to keep the repository in pure Javascript. Is there a particular reason you'd like to make the conversion?

On a similar vein, what does your backend stack look like? I'm using Hapi and I've gotten things working with regards to JSON API, but I'd prefer a more integrated, cleaner approach.

**Comment by ShadowManu** [comment]
The reasons for using Typescript on this project are the same reasons for using typescript itself: mainly static checks, tooling and ES6 features. We have plans of using typescript in the frontend too (angular 1 & 2), so its interesting to see some results of using it on a smaller scale.

Regarding our backend stack, its Hapi-Bookshelf-Postgres. I've been looking for some tools like [endpoints](https://github.com/endpoints/endpoints) which looked nice at the beginning but it was too ambitious on the goal, so it is very coupled on its code. So I ended up here, hoping a more modular approach (but still expecting to make another tool for hapi easier usage of json api).

**Comment by jamesdixon** [comment]
Understood. I do understand the benefits of Typescript, but again, would prefer to stick with ES6. The benefits that Typescript provides are great, especially for large-scale projects, but I think the benefits may outweigh the effort in converting this addon.

All that said, we are using the same exact backend stack, so I believe it would be worthwhile for us to collaborate on the project as long as you're OK with sticking to pure JS rather Typescript. I too looked at Endpoints, but the project seemed to be relatively stagnant. I have a couple of Hapi plugins that I created to assist with JSON API and would be more than happy to share. Let me know.

James

**Comment by ShadowManu** [comment]
I have no problem of moving the existing codebase to typescript (which in fact I'm already doing). Still prefer ES5/6?

As a side note, any other chat-like channel we can discuss over?

**Comment by jamesdixon** [comment]
Feel free to msg me on gChat/Hangouts at jim.w.dixon@gmail.com and we can discuss further
